### ISSUE TITLE
 jchem version related question

### ISSUE THREAD

**Issue by INHYEOKSONG** [clinfo/ReTReK#2]
error syntax :

(retrek) root@12d7c7a2ac87:~/ReTReK# javac CxnUtils.java
CxnUtils.java:1: error: cannot access ValenceErrorChecker
import chemaxon.checkers.ValenceErrorChecker;
                        ^
  bad class file: /opt/opt/chemaxon/jchemsuite/lib/com.chemaxon-structurechecker.jar(chemaxon/checkers/ValenceErrorChecker.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.

question:

Currently, only jchem version 20.19 is available. I wonder if there is no way to use it other than the 20.13 version suggested in the instructions.

Could you please share the version linux installation file?

**Comment by sishida21** [comment]
@INHYEOKSONG 
I apologize for the late reply. We cannot share the installation file due to the License Agreement of ChemAxon. I think that version 20.19 is also compatible with version 20.13, although I cannot confirm this due to the expiration of the Academic license.

We have now released the pure Python version of ReTReK ([clinfo/ReTReKpy](https://github.com/clinfo/ReTReKpy)) that does not use ChemAxon, so please consider using that as well.
